### ISSUE TITLE
rsvg-convert for older Kindle (3rd gen keyboard)

### ISSUE THREAD

**Issue by jamorris** [flabby1976/weather-on-kindle4nt#6]
Do you have any suggestions for finding a version of rsvg-convert for the Kindle keyboard (3rd gen)? Pngcrush works but not rsvg-convert so I can't get a final .png file to display.

**Comment by flabby1976** [comment]
Hi - apologies, I have only just noticed this message. Not sure I can help with a rsvg-convert binary for a different kindle version I'm afraid - I just copied the versions from 'scolby33' at https://github.com/scolby33/weather_kindle and he seems to have got them from the Debian APT repository if that's any help?

**Comment by jamorris** [comment]
Thanks. I was able to get rsvg-convert running in a chroot environment on the Kindle.
